services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./auction-service/.env

  postgres-auction:
    image: postgres:15.1
    container_name: db-auction
    env_file:
      - ./auction-service/.env
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

  postgres-bidder:
    image: postgres:15.1
    container_name: db-bidder
    env_file:
      - ./bidder-service/.env
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  auction-service:
    container_name: auction-service
    restart: always
    env_file:
      - ./auction-service/.env
    ports:
      - "3000:3000"
    build:
      context: ./auction-service
      target: run

  bidder-service:
    container_name: bidder-service
    restart: always
    env_file:
      - ./bidder-service/.env
    ports:
      - "3001:3001"
    build:
      context: ./bidder-service
      target: run

volumes:
  redis-data:
